### ISSUE TITLE
训练到第2个epoch时卡住

### ISSUE THREAD

**Issue by gitctrlx** [code-cp/nanogpt-burn#1]
作者您好，当我构建并运行您的项目时遇到了一个问题，就是训练到第2个epoch的时候就卡住不动了，gpu占用也降下来了，请问这是什么原因？卡在如下图的地方：
![image](https://github.com/code-cp/nanogpt-burn/assets/76150709/c177a446-25ae-404e-84ca-8c8499a1cc39)

**Comment by code-cp** [comment]
我用wgpu训练的时候也遇到过卡住的情况，我觉得可能是用来训练的gpu算力/内存不够，建议降低batch size, block size这些参数再试试，如果还是不能训练，可以换更好的gpu，或者去https://github.com/tracel-ai/burn提交一个issue
